name: Enviar Parte Cerro Laderas cada 4 horas

on:
  schedule:
    - cron: '0 */4 * * *'

  workflow_dispatch:


jobs:
  send_to_telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper and send to Telegram
      env:
        CHAT_ID_TELEGRAM: ${{ secrets.CHAT_ID_TELEGRAM }}
        TOKEN_TELEGRAM_BOT: ${{ secrets.TOKEN_TELEGRAM_BOT }}
      run: python3 scraper_cerro_laderas.py
